# Generated by Django 3.2 on 2021-05-20 14:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_state', models.IntegerField(db_index=True, default=0)),
                ('source', models.CharField(db_index=True, default='', max_length=64)),
                ('date_to_add', models.DateField(db_index=True, default=datetime.datetime(2021, 5, 20, 14, 33, 7, 435795, tzinfo=utc))),
                ('name', models.CharField(db_index=True, max_length=64, unique=True)),
                ('gender', models.CharField(db_index=True, default='', max_length=1)),
                ('wechat_num', models.CharField(db_index=True, default='', max_length=64, unique=True)),
                ('area', models.CharField(db_index=True, default='', max_length=64)),
                ('phone', models.CharField(db_index=True, default='', max_length=64)),
                ('little_assistant', models.CharField(db_index=True, default='', max_length=64)),
                ('consultant', models.CharField(db_index=True, default='', max_length=64)),
                ('service_consultant', models.CharField(db_index=True, default='', max_length=64)),
                ('paper_writer', models.CharField(db_index=True, default='', max_length=64)),
                ('identity', models.IntegerField(default=0)),
                ('school_type', models.CharField(db_index=True, default='', max_length=64)),
                ('school', models.CharField(db_index=True, default='', max_length=64)),
                ('curriculum_system', models.CharField(db_index=True, default='', max_length=64)),
                ('curriculum_system_note', models.CharField(db_index=True, default='', max_length=64)),
                ('graduation_date', models.DateField(db_index=True, default=datetime.datetime(2021, 5, 20, 14, 33, 7, 435795, tzinfo=utc))),
                ('application_level', models.CharField(db_index=True, default='', max_length=64)),
                ('major', models.CharField(default='', max_length=64)),
                ('target_country', models.CharField(default='', max_length=64)),
                ('GPA', models.CharField(default='', max_length=64)),
                ('TOEFL', models.CharField(default='', max_length=64)),
                ('IELTS', models.CharField(default='', max_length=64)),
                ('SAT', models.CharField(default='', max_length=64)),
                ('ACT', models.CharField(default='', max_length=64)),
                ('GRE', models.CharField(default='', max_length=64)),
            ],
        ),
    ]
