# Generated by Django 3.2 on 2021-05-20 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_to_add',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='graduation_date',
            field=models.DateField(db_index=True, null=True),
        ),
    ]
